### ISSUE TITLE
v0.30.0 changes

### ISSUE THREAD

**Issue by na--** [k6io/docs#191]
Just a reminder we need some changes here after k6 v0.30.0 is release. I can try to do them tomorrow if anyone else is not interested. 

Related PRs: https://github.com/loadimpact/k6/pull/1809 and https://github.com/loadimpact/jslib.k6.io/pull/20.

**Comment by na--** [comment]
And a reminder we should update https://k6.io/docs/examples/data-parameterization and probably also https://k6.io/docs/testing-guides/running-large-tests now that we have `SharedArray`

**Comment by na--** [comment]
I'll write up the docs about https://github.com/loadimpact/k6/blob/master/release%20notes/v0.30.0.md#support-a-handlesummary-callback-at-the-end-of-the-test-1768, though I have no idea where to position them in the menus... :confused: 

I guess I can mention `handleSummary()` above https://k6.io/docs/getting-started/results-output#summary-export, and I can add a mention in https://k6.io/docs/using-k6/test-life-cycle, but I have no idea where to put the page with the summary info... Maybe on the top of the "Results visualization" part of the left menu?

@ppcano @simskij, any preferences or suggestions?

**Comment by ppcano** [comment]
@na-- 
Perhaps, a nested page of the test-life-cycle? 


If you think this page is an advanced feature and should not appear on the sidebar menu,  there is a frontmatter option to not being shown on the menu.

**Comment by na--** [comment]
hmm it probably should appear in the menu, but the best title I can think of is `End-of-test summary` :sweat_smile:
