### ISSUE TITLE
v0.31: Update `JavaScript Compatibility Mode` page

### ISSUE THREAD

**Issue by ppcano** [k6io/docs#232]
[v0.31 release](https://github.com/loadimpact/k6/releases/tag/v0.31.0) states:

> JS: Because of the awesome improvements to goja, the JS runtime k6 uses, it's no longer necessary for k6 to load core.js to polyfill missing JS features when using the default --compatibility-mode=extended. So in v0.31.0 core.js has been dropped entirely, yielding some significant CPU and memory usage improvements. The actual numbers will depend on the use case, but for simple tests users can expect a memory drop of about 2MB per VU (from ~2.7MB to ~600KB), and a slight CPU decrease of about 5-10%. For more complex tests with a lot of JS code this benefit won't be as pronounced. Another benefit of this change is that initializing VUs and starting a test is substantially faster than before!

Probably,  some parts of the [Compatibility Mode page](https://k6.io/docs/using-k6/javascript-compatibility-mode) need to be updated.

**Comment by MStoykov** [comment]
fixed in 0d2b6d800c5379238b2a67d47712feea7baab4ec
