### ISSUE TITLE
Document that the summary export threshold is unintuitive

### ISSUE THREAD

**Issue by MStoykov** [k6io/docs#30]
When the summary export was written no one noticed that the boolean used to say whether a threshold has passed or not is `true` when it failed and `false` when it has passed, which confusing to users.

I think this should be documented better and we should have an example of a threshold 

links:
[original PR](https://github.com/loadimpact/k6/pull/1168)
[community forum link](https://community.k6.io/t/summary-export-command/438)
[k6 issue](https://github.com/loadimpact/k6/issues/1498)

**Comment by na--** [comment]
This is somewhat connected to https://github.com/loadimpact/k6/pull/1768 - that PR will preserve the current `--summary-export` format as it is, for backwards compatibility, but the data format we will pass to `handleSummary()` will be saner. As an example:
```json
{
    "metrics": {
        "http_req_duration": {
            "type": "trend",
            "contains": "time",
            "values": {
                "p(80)": 277.99444800000003,
                "p(99.99)": 408.53503457669984,
                "avg": 202.9503869583333,
                "min": 132.286877,
                "med": 152.79688099999998,
                "p(70)": 271.7887037,
                "count": 120,
                "max": 408.674962,
                "p(90)": 280.83382650000004,
                "p(95)": 339.6004894,
                "p(99)": 395.77117560000005
            },
            "thresholds": {
                "p(95)<500": {
                    "ok": true
                }
            }
        },
    }
}
```
