### ISSUE TITLE
IP Range list is broken

### ISSUE THREAD

**Issue by Scorito-Dev** [k6io/docs#305]
When I click on the URl in your documentation that leads to https://k6.io/docs/cloud/cloud-faq/what-ip-addresses-are-used-by-the-k6-cloud it tells me its broken. I need to know what IP Addresses to whitelist

**Comment by simskij** [comment]
Yeah, the link should be https://k6.io/docs/cloud/cloud-faq/general-questions/#what-ip-addresses-are-used-by-the-k6-cloud. Where did you find this link?
