### ISSUE TITLE
Introductory content on testing with xk6

### ISSUE THREAD

**Issue by simskij** [k6io/docs#338]
A more factual/docsy version of what @imiric wrote for the blog at https://k6.io/blog/extending-k6-with-xk6/. Should include:

- How to build an xk6 binary
- How to utilize built-in modules in your script
- Considerations and drawbacks for different running modes, like:
  - Locally
  - Operator
  - Cloud

**Comment by imiric** [comment]
@simskij Could we reuse #169 for this?

I started today on these docs so the suggestion is valuable, just having a single issue would be preferable.

**Comment by simskij** [comment]
Yes, makes sense! 👍🏽
